services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gg_cafe
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

