/*
CafeServerGo
A custom TCP socket server hosting library / game server.
Copyright (C) 2026 BXn4 and Hurka5
*/

package commands

type ErrorCodes int

// Game errros (SENDING TO CLIENT)
const (
	NO_ERROR ErrorCodes = 0

	// BASIC
	NOT_ENOUGHT_MONEY = 4

	ACHIEVEMENT_ERROR = 1
	VERSION_OUTDATED  = 1

	CANT_USE_CHAT_FOR_X_DAYS_WITH_REASON = 1
	JOB_ACCEPTED                         = 1
	JOB_DECLINED                         = 2
	ENOUGH_WORK_TODAY                    = 2
	ADDFRIEND_DENIED                     = 2
	YOU_GOT_REPORTED_WITH_REASON         = 2

	CHAT_WARN = 3

	CHAT_LINK_SENT = 4
	UNKNOWN_GIFT   = 5

	MUFFIN_MINIGAME_GOLD_LEVEL_NOT_REACHED     = 9
	CHANGE_PASSWORD_MISSMATCH                  = 10
	CHANGE_PASSWORD_NO_REGISTERED_PLAYER_FOUND = 11
	LOGIN_WRONG                                = 11
	JOB_PLAYER_LEFT                            = 11

	INVITE_FRIEND_PLAYER_ALREADY_REGISTERED = 13
	INVITE_FRIEND_EMAIL_NOT_VALID           = 14
	LOGIN_INCORRECT                         = 14

	CREATE_AVATAR_USER_ALREADY_HAVE_AVATAR = 15
	LOGIN_LOGGED_IN                        = 15
	LOGIN_FAULTY_AVATAR                    = 16
	LOGIN_TRY_LOGIN                        = 16

	LOGIN_SET_FIRST_LOGIN        = 17
	CREATE_AVATAR_NAME_INCORRECT = 18
	LOGIN_PLAYER_BANNED          = 19

	CAFE_PRIVATE           = 20
	MARKET_PLACE_FULL      = 20
	ALREADY_IN_SAME_CAFE   = 21
	ALREADY_IN_MARKETPLACE = 21
	CAFE_NOT_EXIST         = 22
	CHAT_DISABLED          = 23
	WALK_CANT_GO_THERE     = 23
	DONT_SPAM_CHAT         = 24

	SHOP_SELL_ITEM_NOT_AVAILABLE = 41

	EDIT_EXTEND_ALREADY_BOUGHT = 53
	EDIT_EXTEND_CANT_BUY_YET   = 54

	CREATE_AVATAR_NAME_IS_USED          = 62
	JOB_PLACE_CURRENT_DISH_BEFORE_CLEAN = 63

	// EDITOR
	ERROR_EDITOR_WATCH_OUT                  = 1
	ERROR_EDITOR_LEVEL_NOT_REACHED          = 3
	ERROR_EDITOR_SELL_ITEM_NOT_IN_STOCK     = 32
	ERROR_EDITOR_STORE_OBJ_DISH_ON_TOP_THIS = 37
	ERROR_EDITOR_ONLY_IN_EDITOR             = 38
	ERROR_EDITOR_POSITION_NOT_VALID         = 39
	ERROR_EDITOR_STORE_FIELD_EMPTY          = 51

	// COOP_LOW_LEVEL
	ERROR_COOP_JOIN_LOW_LEVEL  = 3
	ERROR_COOP_JOIN_LEVEL_HIGH = 7
	ERROR_COOP_JOIN_FULL       = 85
	ERROR_COOP_JOIN_MAX_DONE   = 87

	// REGISTER
	USERNAME_WRONG                = 1
	USERNAME_SHORT                = 2
	USERNAME_LONG                 = 3
	PASSWORD_WRONG                = 5
	PASSWORD_INVALID              = 10
	LOGIN_USER_ALREADY_REGISTERED = 12
	REGISTER_ERROR                = 12
	ACCOUNT_EXIST                 = 13
	EMAIL_INVALID                 = 14
	REGISTER_REGISTERED           = 16
	BAD_WORD                      = 93
	EMAIL_LONG                    = 94
	PASSWORD_SHORT                = 96
	ACCEPT_TERMS                  = 98

	// FASTFOOD
	ERROR_FASTFOOD_EMPTY            = 103
	ERROR_FASTFOOD_OUT_OF_REACH     = 36
	ERROR_FASTFOOD_OBJECT_NOT_FOUND = 999

	// GIFTS
	ERROR_GIFT_USE_NO_FREE_COUNTER = 20
	ERROR_FRIDGE_FULL              = 40

	// JOBS
	ERROR_JOB_REFILL_ONCE_A_DAY              = 61
	ERROR_JOB_HIRE_TARGET_PLAYER_OUT_OF_JOBS = 61

	// WHELL MINIGAME
	ERROR_WHEEL_MINIGAME_NO_GIFT_SPACE_LEFT = 92

	// STAFF RENAME / HIRE / FIRE
	ERROR_STAFF_RENAME_NAME_INVALID = 12
	ERROR_STAFF_HIRE_IMPOSSIBLE     = 1
	ERROR_STAFF_FIRE_IMPOSSIBLE     = 1

	// CARRIER PIGEON
	ERROR_COURIER_INGREDIENT_NOW_AVAILABLE = 42
	ERROR_COURIER_SHIPPING_ERROR           = 43
)

// Validator errors
const (
	NOT_IMPLEMENTED = 1000 + iota
	MIN_ARGS
	MAX_ARGS
	INVALID_ARGS
	LOCATION_NOT_RUNNING

	CONVERT_ERROR
	INVALID_VALUE
	NOT_DECLARED
)
